[package]
name = "baccarat_drivers"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "baccarat_drivers_lib"
path = "src/lib.rs"

[[bin]]
name = "baccarat_simulator"
path = "src/baccarat_simulator/main.rs"

[[bin]]
name = "baccarat_solver_service"
path = "src/baccarat_solver_service/main.rs"

[dependencies]
baccarat = { path = "../baccarat" }
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
home = "0.5"
actix-web = "4.3"
rust-embed = "6.8"
mime_guess = "2.0"

[features]
embed_website_assets = []
